version: "3"

services:
  builder:
    build:
      context: builder
    image: eosio/builder

  nodeosd:
    build:
      context: .
    image: eosio/eos
    command: /opt/eosio/bin/nodeosd.sh --data-dir /opt/eosio/bin/data-dir
    hostname: nodeosd
    ports:
      - 8888:8888
      - 9876:9876
    expose:
      - "8888"
    volumes:
      - /data/nodeosd:/opt/eosio/bin/data-dir

  keosd:
    image: eosio/eos
    command: /opt/eosio/bin/keosd --wallet-dir /opt/eosio/bin/data-dir
    hostname: keosd
    links:
      - nodeosd
    volumes:
      - /data/keosd:/opt/eosio/bin/data-dir
